In [1]:
import pandas as pd

df = pd.read_csv('test.csv')

In [2]:
df.head()

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy

In [3]:
df.describe()

             Index      day  NumberofLanes   Temperature
count  41778.00000  41778.0   41778.000000  40429.000000
mean   20888.50000     49.0       2.068984     16.457339
std    12060.41411      0.0       0.988519      7.351067
min        0.00000     49.0       1.000000    -21.314645
25%    10444.25000     49.0       1.000000     11.527029
50%    20888.50000     49.0       2.000000     16.471232
75%    31332.75000     49.0       3.000000     21.365883
max    41777.00000     49.0       5.000000     45.230408

In [4]:
df.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
RoadType          324
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      1349
Weather           431
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['Index'].value_counts()

Index
0        1
1        1
2        1
3        1
4        1
        ..
41773    1
41774    1
41775    1
41776    1
41777    1
Name: count, Length: 41778, dtype: int64

In [8]:
df['geohash'].value_counts()

geohash
qp02zs    47
qp08bh    47
qp08bk    47
qp02zj    47
qp02zt    47
          ..
qp09vh     1
qp09m3     1
qp08cv     1
qp09kq     1
qp0dhu     1
Name: count, Length: 1190, dtype: int64

In [9]:
df['day'].value_counts()

day
49    41778
Name: count, dtype: int64

In [10]:
df['timestamp'].value_counts()

timestamp
4:30     939
4:45     932
5:0      932
4:0      928
4:15     926
5:30     926
5:15     923
9:0      922
5:45     918
2:30     915
3:45     909
10:0     909
3:30     908
6:15     904
9:15     904
9:30     904
7:15     903
6:0      901
8:45     901
9:45     898
3:0      897
6:45     897
11:0     897
2:45     896
3:15     896
8:0      895
6:30     894
7:0      893
7:30     892
10:30    890
7:45     889
10:15    889
2:15     887
8:30     884
8:15     881
10:45    880
12:0     878
11:30    876
11:45    871
11:15    870
12:15    856
12:30    847
12:45    834
13:0     815
13:15    805
13:30    790
13:45    777
Name: count, dtype: int64

In [11]:
df['RoadType'].value_counts()

RoadType
Residential    33775
Highway         4272
Street          3407
Name: count, dtype: int64

In [12]:
df['NumberofLanes'].value_counts()

NumberofLanes
1    14828
2    12422
3    12406
4     1062
5     1060
Name: count, dtype: int64

In [13]:
df['LargeVehicles'].value_counts()

LargeVehicles
Not Allowed    26178
Allowed        15600
Name: count, dtype: int64

In [14]:
df['Landmarks'].value_counts()

Landmarks
Yes    28245
No     13533
Name: count, dtype: int64

In [15]:
df['Temperature'].value_counts()

Temperature
6.476213     1
22.318203    1
18.266162    1
8.942256     1
21.698032    1
            ..
19.588991    1
10.735538    1
13.223750    1
12.510917    1
20.363693    1
Name: count, Length: 40429, dtype: int64

In [16]:
df['Weather'].value_counts()

Weather
Sunny    15078
Foggy    11102
Rainy    11081
Snowy     4086
Name: count, dtype: int64